version: '3.7'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - backend

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    build:
      context: ../
      dockerfile: web/backend/api_only.dockerfile
    command: celery -A app.tasks --broker=redis://redis:6379/0 --result-backend=redis://redis:6379/0 worker -l info -c 4 -Ofair --without-gossip --without-mingle
    env_file:
      - backend/.env
    depends_on:
      - redis

  flower:
    build:
      context: ../
      dockerfile: web/backend/api_only.dockerfile
    command: celery -A app.tasks --broker=redis://redis:6379/0 --result-backend=redis://redis:6379/0 flower
    env_file:
      - backend/.env
    ports:
        - 5555:5555
    depends_on:
      - redis

  backend:
    build:
      context: ../
      dockerfile: web/backend/api_only.dockerfile
    env_file:
      - backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
